In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# shape(3,)인 ndarray 생성

In [2]:
data = np.array(range(3))

In [3]:
data

array([0, 1, 2])

In [4]:
data.shape

(3,)

In [5]:
# data2 = np.zeros((2,3))
data2 = np.array([range(3),range(3)])

In [6]:
data2

array([[0, 1, 2],
       [0, 1, 2]])

In [7]:
data2.shape

(2, 3)

In [8]:
data3 = np.zeros((2,3,2))

In [9]:
data3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
data3.shape

(2, 3, 2)

In [15]:
data4 = np.ones((1,2), dtype = np.str)

In [16]:
data4

array([['1', '1']], dtype='<U1')

In [17]:
data4.shape

(1, 2)